__Exercice 1 : Opérations NumPy de base__

In [3]:
import numpy as np

In [4]:
liste=np.array([1, 2, 3, 4, 5])
liste

array([1, 2, 3, 4, 5])

In [5]:
print(liste.sum())
print(liste.mean())
print(liste.prod())


15
3.0
120


In [9]:
for i in liste:
    print(i**i)

1
4
27
256
3125


__Exercice 2 : Produit Matriciel__

In [1]:
import numpy as np
A=np.random.rand(3,2)
B=np.random.rand(2,4)
print("La matrice A est ",A)
print("La matrice B est ",B)

La matrice A est  [[0.98842711 0.97859191]
 [0.63799144 0.72949849]
 [0.58253443 0.37847642]]
La matrice B est  [[0.91132332 0.83157887 0.5747993  0.24117655]
 [0.99606196 0.11211485 0.72421557 0.38329586]]


In [2]:
result=np.dot(A,B)
print('le produit de ces deux matrices est:',result)

le produit de ces deux matrices est: [[1.87551485 0.93166978 1.27685871 0.61347567]
 [1.30804218 0.61232781 0.8950312  0.43348233]
 [0.90786317 0.52685615 0.60893889 0.28556209]]


__Exercice 3 : Extraction de Données___


In [5]:
A=np.random.rand(5,5)
print(A)
for j in A:
    print(j[2])

[[0.79058547 0.76616742 0.61915493 0.05540072 0.82293149]
 [0.3472508  0.90529064 0.09776753 0.29406071 0.96781102]
 [0.38652131 0.31805651 0.43225598 0.83887898 0.11453864]
 [0.17732604 0.01631926 0.88521228 0.14156961 0.00389014]
 [0.80665417 0.13115837 0.91359618 0.85307365 0.71024037]]
0.6191549285186381
0.097767526747229
0.43225598442531754
0.8852122763618178
0.9135961806183204


___Exercice 4 : Opérations statistiques__

In [8]:
tab=np.random.rand(3,4)
print('la somme de chaque colonne:', np.sum(tab,axis=0))
print('la moyenne de chaque ligne:',np.mean(tab,axis=1))
print('le max de tableau:',np.max(tab))
print('le min de tableau:', np.min(tab))
print('la somme de chaque colonne:',np.std(tab,axis=0))



    

la somme de chaque colonne: [1.21624223 1.11812854 2.59837532 1.39003603]
la moyenne de chaque ligne: [0.55018012 0.59102581 0.43948961]
le max de tableau: 0.9694851544040808
le min de tableau: 0.12258066310393667
la somme de chaque colonne: [0.35965118 0.28664873 0.09320086 0.21549139]


___Exercice 5 : Indexation avancée___

In [14]:
tab=np.random.rand(4,5)
cols=tab[:,[1,3]]
print(cols)

elem=tab[tab>0.5]
print(elem)

elements=tab[0:2,:3]
print(elements)

[[0.95898248 0.46875776]
 [0.69945978 0.9823348 ]
 [0.45869256 0.0227536 ]
 [0.66419775 0.88773161]]
[0.95898248 0.59544031 0.69945978 0.9823348  0.74394959 0.54858432
 0.8960928  0.66419775 0.88773161 0.57229688]
[[0.44805227 0.95898248 0.0974667 ]
 [0.59544031 0.69945978 0.04106091]]


___Exercice 6 : Concaténation et division___

In [15]:
arr1=np.random.rand(3,3)
arr2=np.random.rand(3,3)
concatenated_matrix=np.hstack((arr1,arr2))
print(concatenated_matrix)
split_matrices=np.hsplit(concatenated_matrix,2)
print(split_matrices)


[[0.69092964 0.40409921 0.54771566 0.14347197 0.98425689 0.12399011]
 [0.43270339 0.17276419 0.78151333 0.99921055 0.14397261 0.61289993]
 [0.40800847 0.6316896  0.02250166 0.62710671 0.30647503 0.62987583]]
[array([[0.69092964, 0.40409921, 0.54771566],
       [0.43270339, 0.17276419, 0.78151333],
       [0.40800847, 0.6316896 , 0.02250166]]), array([[0.14347197, 0.98425689, 0.12399011],
       [0.99921055, 0.14397261, 0.61289993],
       [0.62710671, 0.30647503, 0.62987583]])]


___Exercice 7 : Broadcasting__

In [18]:
tabl=np.random.rand(3,3)
arr=np.array([1,2,3])
result=tabl+arr
print(result)

[[1.6010666  2.80143974 3.19037644]
 [1.21257686 2.34982455 3.87751639]
 [1.37529726 2.93518122 3.34959976]]


___Exercice 8 : Opérations matricielles avancées___

In [24]:
mat1=np.random.rand(3,3)
mat2=np.random.rand(3,1)
matric_mult=np.dot(mat1,mat2)
print("le multiple des matrices :",matric_mult)

det_A=np.linalg.det(A)
print("le determinant des matrices :",det_A)
inv_A=np.linalg.inv(A)
print("l'inverse des matrices :",inv_A)


le multiple des matrices : [[0.94027663]
 [0.72858355]
 [0.3320106 ]]
le determinant des matrices : -0.2197783586175521
l'inverse des matrices : [[ 1.96861611 -1.88022573  0.61635665 -1.66722229  0.19085942]
 [ 0.59067182  0.38515311  1.1818865   0.41424395 -1.40209012]
 [-0.26295247  0.29990789 -0.2678461   1.48239116 -0.06892072]
 [-0.86306534  0.40260584  0.80899427 -0.16800799  0.32184843]
 [-0.97005648  1.194988   -1.54543383  0.11201353  1.15220655]]


___Exercice 9 : Calcul de normes___

In [ ]:
v=